"""add lc_upload col

Revision ID: 15b5fd757927
Revises: 63dc798dbe80
Create Date: 2025-04-01 19:53:11.054210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b5fd757927'
down_revision = '63dc798dbe80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_norad', 'sat_for_view', ['norad'])
    # op.create_unique_constraint('uq_cospar', 'sat_for_view', ['cospar'])
    op.add_column('user', sa.Column('sat_lc_upload', sa.Boolean(), server_default="false", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sat_lc_upload')
    # op.drop_constraint('uq_norad', 'sat_for_view', type_='unique')
    # op.drop_constraint('uq_cospar', 'sat_for_view', type_='unique')
    # ### end Alembic commands ###
