"""add site and lsp

Revision ID: 7cd7f54cc01d
Revises: 
Create Date: 2022-08-11 21:24:26.991309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd7f54cc01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lightcurve', sa.Column('site', sa.String(length=50), nullable=True))
    op.add_column('lightcurve', sa.Column('lsp_period', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lightcurve', 'lsp_period')
    op.drop_column('lightcurve', 'site')
    # ### end Alembic commands ###
