name: Update Coverage Badge

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update-coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest 
          TEST_STATUS=$?
          echo "Test Status: $TEST_STATUS"

      - name: Set badge color for test result
        run: |
          TEST_STATUS=${{ steps.test-run.outcome }}
          
          # Якщо всі тести пройшли, то Test Status = success, інакше = failure
          if [ "$TEST_STATUS" == "success" ]; then
            TEST_BADGE_COLOR="brightgreen"
            TEST_BADGE_MESSAGE="tests passed"
          else
            TEST_BADGE_COLOR="red"
            TEST_BADGE_MESSAGE="tests failed"
          fi
          
          # Створюємо JSON для значка тестів
          echo "{
            \"schemaVersion\": 1,
            \"label\": \"tests\",
            \"message\": \"$TEST_BADGE_MESSAGE\",
            \"color\": \"$TEST_BADGE_COLOR\"
          }" > test_status_shields.json

      - name: Set badge for coverage result
        run: |
          # Зчитуємо ваш coverage.json і генеруємо формат для Shields.io
          COVERAGE=$(jq -r '.totals.percent_covered_display' coverage.json)
          COLOR="brightgreen"

          # Перевірка на покриття менше ніж 50%
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            COLOR="yellow"
          fi

          # Створюємо новий JSON для Shields.io
          echo "{
            \"schemaVersion\": 1,
            \"label\": \"coverage\",
            \"message\": \"$COVERAGE%\",
            \"color\": \"$COLOR\"
          }" > coverage_shields.json
          
      - name: Commit and push coverage badge update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add coverage_shields.json test_status_shields.json
          git commit -m "Update coverage and test status badges"
          git push
